[package]
name = "x509"
version = "0.1.0"
authors = ["Daniel Basedow <daniel.basedow@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
num-bigint = "0.2"
ring = "0.14.6"
untrusted = "0.6"

[dev-dependencies]
hex = "0.3"
