[package]
name = "fuzz"
version = "0.1.0"
authors = ["Daniel Basedow <daniel.basedow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.x509]
path = ".."

[dependencies]
afl = "0.4"
